ur3:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Position Controllers ---------------------------------------
    shoulder_pan_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_pan_joint
        pid: {p: 500.0, i: -20.0, d: 50.0}

    # Position Controllers ---------------------------------------
    shoulder_lift_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_lift_joint
        pid: {p: 8000.0, i: 20.0, d: 10.0}

    # Position Controllers ---------------------------------------
    elbow_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: elbow_joint
        pid: {p: 2500.0, i: -250.0, d: 15.0}

    # Position Controllers ---------------------------------------
    wrist_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist_1_joint
        pid: {p: 20.0, i: 1.0, d: 5.0}

    # Position Controllers ---------------------------------------
    wrist_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist_2_joint
        pid: {p: 30.0, i: -5.0, d: 5.0}

    # Position Controllers ---------------------------------------
    wrist_3_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist_3_joint
        pid: {p: 5.0, i: 1.0, d: 1.0}
